channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip

  - pytorch
  - pytorch-cuda
  - torchvision
  - transformers
  - datasets

  - scikit-learn
  - pandas

  - rich
  - typer
  - shellingham
  - loguru

  - black
  - isort
  - flake8
  - flake8-bugbear
  - mypy
  - ipywidgets
  - pre-commit
